[package]
name = "treesv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-money = "0.4.1"
indoc = "2.0.4"
tempfile = "3.10.0"
